name: python-unittest
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python3 -m pip install coverage
    - name: Test with unittest
      run: |
        coverage run -m unittest discover -s tests/ -p '*.py'
        coverage report -m